rvm:
  - 2.1.5

cache: bundler
before_script:
  - 'git submodule init'
  - 'git submodule update'
  - 'cd spec/dummy/'
  - 'cp .env.example ../../.env'
  - './bin/bootstrap'
  - 'bundle exec rake db:migrate'
  - 'rm -rf spec/'
  - 'cd ../../'

script:
  - 'bundle exec rspec'

notifications:
  webhooks: http://dune-investissement.herokuapp.com/projects/a23a5977-8a4d-4760-a8a4-77755486dc59/status
