FORMAT: 1A
HOST: https://neighbor.ly/api/

# Neighbor.ly
Here you will find how to integrate an application with Neighbor.ly. Check our [Dashboard source code](https://github.com/neighborly/neighborly-dashboard) for a real use case.

# Sessions
Your first stop when integrating with Neighborly. For a lot of endpoints, you are expected to provide an `access_token`, managed by this section.


## Sessions [/sessions]
### Create a session [POST]

+ Request

    + Header

            Accept: application/vnd.api+json;revision=1

    + Body

            { "email": "mr.nobody@example.com", "password": "your-really-strong-password" }

+ Response 201 (application/json)

        { "access_token": "Ndf6kxgLfr_KMhAg8wMpm7Yit2cvHkv9oI8qIXWiHmZdeqI1h0cmn8p4wCEhoZS-AQY", "user_id": 1 }

+ Response 400 (application/json)

        {}


+ Response 401 (application/json)

        {}


# Users


## Users [/users/:id]
### Fetch user information [GET]

+ Request

    + Header

            Accept: application/vnd.api+json;revision=1
            Authorization: Token your-token-here


+ Response 200 (application/json)

        { "user": { "id": 34, "bio": null, "created_at": "2014-07-01T16:21:35+00:00", "display_image": "https://gravatar.com/avatar/7fc04373cf0c63e376baec602fec8f45.jpg?size=150&default=http://localhost/assets/default-avatars/5.png", "display_name": "Joãozinho", "email": "person0.9132588986740293@example.com", "facebook_url": null, "linkedin_url": null, "other_url": null, "profile_type": "personal", "twitter_url": null } ] }

# Tags

Requires user to be an admin.


## Tags (/users)
### Create a tag [POST]

+ Request

    + Header

            Accept: application/vnd.api+json;revision=1
            Authorization: Token your-token-here

    + Body

            {"tag"=>{"name"=>"foobar", "visible": true}}

+ Response 201 (application/json)

        {"tag":{"id":310,"name":"foobar","visible":true}}

+ Response 400 (application/json)

        {}


+ Response 401 (application/json)

        {}

+ Response 422 (application/json)

        {"errors":{"name":["has already been taken"]}}

